USE codeup_test_db2;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist  VARCHAR(100),
name    VARCHAR(100),
release_date SMALLINT  UNSIGNED,
sales   DECIMAL(14,2),
genre  VARCHAR(100),
PRIMARY KEY(id)

)

